### PR TITLE
Recipe List GUI and JSON Input File

### PR DESCRIPTION
**Pull request by narenrameshb**
JSON file to be generated from API calls (Gemini or Recipe API)

### CODE REVIEW

**Review by Harpuneet2005 — APPROVED** [review]
Code is clean, clear, and adheres to design principles

**Comment by mfatir-y** [comment]
Looks good!

**Review by mfatir-y — APPROVED** [review]
Looks good!

**Review by EnzaDinza — APPROVED** [review]
Code reviewed, everything looks good and works as expected.

**Pull request merged**
