### PR TITLE
Removed entity access from everywhere but interactors

### PR DESCRIPTION
**Pull request by mfatir-y**
IngredientList repository is not initialized with the correct IDs set for each ingredient. The changes mainly come from using the repository instead of the list of ingredients. I still need to add java docs to my files

### CODE REVIEW

**Comment by narenrameshb** [comment]
We need to resolve conflicts before merging.

**Review by EnzaDinza — COMMENTED** [review]
I've added a few comments. In general, please avoid importing and directly accessing the IngredientListRepository as much as possible. To address the dependency issue, there is an interface for this repository called IngredientRepository, which would be better to use.

**Review by narenrameshb — APPROVED** [review]
Looks good!

**Review by Harpuneet2005 — APPROVED** [review]
Looks good!

**Pull request merged**
