### PR TITLE
m.fatir

### PR DESCRIPTION
**Pull request by mfatir-y**
I refactored the code to follow clean architecture model and added support to move to the next page of app once the image has been uploaded correctly. An alert will be given if invalid image is uploaded with no ingredients. My API key is omitted from the commits.

### CODE REVIEW

**Comment by narenrameshb** [comment]
I reviewed the code. It is syntactically correct, in line with the user story, and follows the required principles.

**Review by Harpuneet2005 — APPROVED** [review]
Changes look great and work well!

**Review by narenrameshb — APPROVED** [review]
The code is well written and abides by project guidelines, as well as our user stories and use cases.

**Review by EnzaDinza — APPROVED** [review]
Looks great! The changes are clean and improve the overall structure.

**Pull request merged**
